spring:
  profiles:
    active: dev # 环境设置
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.210.106:3306/community?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456@Qaz
