server:
  port: 8111 # 服务端口
#  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: community # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://117.50.163.207:3306/community?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123@Qwe
  cloud:
    nacos:
      discovery:
        server-addr: 117.50.163.207:8848
  redis:
    host: 117.50.163.207    #Redis服务器地址
    password: 123@Qaz
    port: 6379              #Redis服务器连接端口
    database: 0             #Redis数据库索引（默认为0）
    timeout: 1800000        #连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20      #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5         #连接池中的最大空闲连接
        min-idle: 0         #连接池中的最小空闲连接

#阿里云文件上传Oss配置
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    keyId: LTAI5tESqSDfQKMBAq1yekez
    keySecret: jhSqTFGZJ5egZl60dLi1uOgOhMdhLZ
    bucketName: srb-yhx


mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/interest/community/mapper/xml/*.xml
mybatis:
  configuration:
    map-underscore-to-camel-case: true
ceshi:
  name: ${测试:测试1}