server:
  port: 8119 # 服务端口
#  port: 8110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: user # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.210.106:3306/user?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456@Qaz
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.210.106:8849
  redis:
    host: 101.43.210.106    #Redis服务器地址
    password: 123456@Qaz
    port: 6379              #Redis服务器连接端口
    database: 0             #Redis数据库索引（默认为0）
    timeout: 1800000        #连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 20      #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5         #连接池中的最大空闲连接
        min-idle: 0

mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/interest/security/mapper/xml/*.xml
  type-aliases-package: com/interest/security/mapper